### ISSUE TITLE
Error DATA BASE Generating new players

### ISSUE THREAD

**Issue by sports23** [owsPro/OWS_for_All_PHP#1]
Database Query Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE T.id=143' at line 1

Database Query Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE T.id=40' at line 1

PHP Version 7.4.33  the same error PHP Version 8.0

**Comment by owsPro** [comment]
Fixed: https://github.com/owsPro/OWS_for_All_PHP/commit/eff9b6384633780a747ed773bf275beb1b84ff82
In addition, the datagenerator class is resolved and provided as static functions.
