### ISSUE TITLE
Stadium Serching in the club no results 

### ISSUE THREAD

**Issue by sports23** [owsPro/OWS_for_All_PHP#3]
Like i said i can assign a stadium to my team... no loading

**Comment by owsPro** [comment]
What exactly is meant?

**Comment by sports23** [comment]
Sorry duplicate issue, but  that is the problem, i can't figure out... what is, searching is still loading but no found the stadium, that is the problem ... Sorry for my bad English..

**Comment by sports23** [comment]
I fund the solution , take a look in the  	itemsprovider.php from the admin folder  	Line 17 error

**### <?php
/*This file is part of "OWS for All PHP" (Rolf Joseph)
  https://github.com/owsPro/OWS_for_All_PHP/
  A spinn-off for PHP Versions 5.4 to 8.2 from:
  OpenWebSoccer-Sim(Ingo Hofmann), https://github.com/ihofmann/open-websoccer.

  "OWS for All PHP" is is distributed in WITHOUT ANY WARRANTY;
  without even the implied warranty of MERCHANTABILITY
  or FITNESS FOR A PARTICULAR PURPOSE.

  See GNU Lesser General Public License Version 3 http://www.gnu.org/licenses/

*****************************************************************************/
								include($_SERVER['DOCUMENT_ROOT'].'/admin/adminglobal.inc.php');$dbTable=$_GET['dbtable'];if(!strlen($dbTable)||preg_match('/^([a-zA-Z1-9_])+$/',$dbTable)==0)throw new Exception('Illegal parameter: dbtable');
								$labelColumns=$_GET['labelcolumns'];if(!strlen($labelColumns)||preg_match('/^([a-zA-Z1-9_,])+$/',$labelColumns)==0)throw new Exception('Illegal parameter: labelcolumns');$search=(isset($_GET['search']))?strtolower($_GET['search']):'';
								$itemId=(isset($_GET['itemid'])&&is_numeric($_GET['itemid']))?$_GET['itemid']:0;$labels=explode(',',$labelColumns);$whereCondition='';if($itemId>0){$whereCondition='id=%d';$queryParameters=$_GET['itemid'];}elseif(!strlen($search)){
								$whereCondition='1=1';$queryParameters='';}else{$first=TRUE;foreach($labels as$labelColumn){if(!$first)$whereCondition.=' OR ';$first=FALSE;$whereCondition.= LOWER('.$labelColumn.')LIKE\'%%%s%%\'';$queryParameters[]=$search;}}
								$whereCondition.=' ORDER BY '.$labelColumns.' ASC';$result=$db->querySelect('id,'.$labelColumns,Config('db_prefix').'_'.$dbTable,$whereCondition,$queryParameters,config(MAX_ITEMS));$items=[];while($item=$result->fetch_array()){$label='';
								$first=TRUE;foreach($labels as$labelColumn){if(!$first)$label.=' - ';$first=FALSE;$label.=$item[trim($labelColumn)];}$items[]=['id'=>$item['id'],'text'=>$label];}$result->free();echo json_encode($items);**


Replace code whit that : 


<?php
/*This file is part of "OWS for All PHP" (Rolf Joseph)
  https://github.com/owsPro/OWS_for_All_PHP/
  A spinn-off for PHP Versions 5.4 to 8.2 from:
  OpenWebSoccer-Sim(Ingo Hofmann), https://github.com/ihofmann/open-websoccer.

  "OWS for All PHP" is is distributed in WITHOUT ANY WARRANTY;
  without even the implied warranty of MERCHANTABILITY
  or FITNESS FOR A PARTICULAR PURPOSE.

  See GNU Lesser General Public License Version 3 http://www.gnu.org/licenses/
*****************************************************************************/
include($_SERVER['DOCUMENT_ROOT'].'/admin/adminglobal.inc.php');

$dbTable = $_GET['dbtable'];
if (!strlen($dbTable) || preg_match('/^([a-zA-Z1-9_])+$/',$dbTable) == 0) {
    throw new Exception('Parametru ilegal: dbtable');
}

$labelColumns = $_GET['labelcolumns'];
if (!strlen($labelColumns) || preg_match('/^([a-zA-Z1-9_,])+$/',$labelColumns) == 0) {
    throw new Exception('Parametru ilegal: labelcolumns');
}

$search = (isset($_GET['search'])) ? strtolower($_GET['search']) : '';
$itemId = (isset($_GET['itemid']) && is_numeric($_GET['itemid'])) ? $_GET['itemid'] : 0;

$labels = explode(',', $labelColumns);
$whereCondition = '';

if ($itemId > 0) {
    $whereCondition = 'id=%d';
    $queryParameters = $_GET['itemid'];
} elseif (!strlen($search)) {
    $whereCondition = '1=1';
    $queryParameters = '';
} else {
    $first = true;

    foreach ($labels as $labelColumn) {
        if (!$first) {
            $whereCondition .= ' OR ';
        }

        $first = false;
        $whereCondition .= ' LOWER(' . $labelColumn . ') LIKE \'%%%s%%\'';
        $queryParameters[] = $search;
    }
}

$whereCondition .= ' ORDER BY ' . $labelColumns . ' ASC';
$result = $db->querySelect('id,' . $labelColumns, Config('db_prefix') . '_' . $dbTable, $whereCondition, $queryParameters, Config('MAX_ITEMS'));
$items = [];

while ($item = $result->fetch_array()) {
    $label = '';
    $first = true;

    foreach ($labels as $labelColumn) {
        if (!$first) {
            $label .= ' - ';
        }

        $first = false;
        $label .= $item[trim($labelColumn)];
    }

    $items[] = ['id' => $item['id'], 'text' => $label];
}

$result->free();
echo json_encode($items);


///////////////  All stadium search and replace work properly for complete!
