### ISSUE TITLE
In the Club no stadion loading after 2 character 

### ISSUE THREAD

**Issue by sports23** [owsPro/OWS_for_All_PHP#4]
In the stadion part of the editing club no loading the stadiums what i create... 
![Stadium](https://github.com/owsPro/OWS_for_All_PHP/assets/150643750/585eac92-223b-45f3-8c26-622f6371e2f6)

**Comment by owsPro** [comment]
There you have to press Enter after the input. The possible hits are not immediately displayed as a preview. What is displayed are the previous search entries.

**Comment by sports23** [comment]
the problem is still browsing nothing happens....
